In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.data')

In [3]:
data.shape

(4600, 58)

In [4]:
data.columns=list(range(57))+['class']
data.shape,data.dropna().shape,data.dtypes

((4600, 58), (4600, 58), 0        float64
 1        float64
 2        float64
 3        float64
 4        float64
 5        float64
 6        float64
 7        float64
 8        float64
 9        float64
 10       float64
 11       float64
 12       float64
 13       float64
 14       float64
 15       float64
 16       float64
 17       float64
 18       float64
 19       float64
 20       float64
 21       float64
 22       float64
 23       float64
 24       float64
 25       float64
 26       float64
 27       float64
 28       float64
 29       float64
 30       float64
 31       float64
 32       float64
 33       float64
 34       float64
 35       float64
 36       float64
 37       float64
 38       float64
 39       float64
 40       float64
 41       float64
 42       float64
 43       float64
 44       float64
 45       float64
 46       float64
 47       float64
 48       float64
 49       float64
 50       float64
 51       float64
 52       float64
 53       float64
 54 

In [5]:
x=data.drop('class',axis=1)
y=data['class']
from sklearn.decomposition import PCA
myalgo=PCA(n_components=5).fit(x)
x=myalgo.transform(x)
x.shape

(4600, 5)

In [6]:
from sklearn.model_selection import train_test_split
x_tr,x_ts,y_tr,y_ts=train_test_split(x,y,test_size=0.2)

In [7]:
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.linear_model import LogisticRegression
algo=LogisticRegression()
algo.fit(x_tr,y_tr)
print(classification_report(y_ts,algo.predict(x_ts)))
algo.score(x_ts,y_ts),confusion_matrix(y_ts,algo.predict(x_ts))

              precision    recall  f1-score   support

           0       0.80      0.86      0.83       567
           1       0.75      0.66      0.70       353

    accuracy                           0.78       920
   macro avg       0.78      0.76      0.77       920
weighted avg       0.78      0.78      0.78       920



C:\Users\pulki\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


(0.7847826086956522, array([[490,  77],
        [121, 232]], dtype=int64))

In [8]:
from sklearn.neighbors import KNeighborsClassifier
algo=KNeighborsClassifier()
algo.fit(x_tr,y_tr)
print(classification_report(y_ts,algo.predict(x_ts)))
algo.score(x_ts,y_ts),confusion_matrix(y_ts,algo.predict(x_ts))

              precision    recall  f1-score   support

           0       0.81      0.80      0.81       567
           1       0.69      0.70      0.69       353

    accuracy                           0.76       920
   macro avg       0.75      0.75      0.75       920
weighted avg       0.76      0.76      0.76       920



(0.7619565217391304, array([[454, 113],
        [106, 247]], dtype=int64))

In [9]:
from sklearn.naive_bayes import GaussianNB
algo=GaussianNB()
algo.fit(x_tr,y_tr)
print(classification_report(y_ts,algo.predict(x_ts)))
algo.score(x_ts,y_ts),confusion_matrix(y_ts,algo.predict(x_ts))

              precision    recall  f1-score   support

           0       0.67      0.94      0.79       567
           1       0.74      0.27      0.40       353

    accuracy                           0.68       920
   macro avg       0.71      0.61      0.59       920
weighted avg       0.70      0.68      0.64       920



(0.683695652173913, array([[533,  34],
        [257,  96]], dtype=int64))

In [10]:
from sklearn.svm import SVC
algo=SVC()
algo.fit(x_tr,y_tr)
print(classification_report(y_ts,algo.predict(x_ts)))
algo.score(x_ts,y_ts),confusion_matrix(y_ts,algo.predict(x_ts))

C:\Users\pulki\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


              precision    recall  f1-score   support

           0       0.85      0.74      0.79       567
           1       0.66      0.80      0.72       353

    accuracy                           0.76       920
   macro avg       0.76      0.77      0.76       920
weighted avg       0.78      0.76      0.77       920



(0.7630434782608696, array([[421, 146],
        [ 72, 281]], dtype=int64))

In [11]:
from sklearn.tree import DecisionTreeClassifier
algo=DecisionTreeClassifier()
algo.fit(x_tr,y_tr)
print(classification_report(y_ts,algo.predict(x_ts)))
algo.score(x_ts,y_ts),confusion_matrix(y_ts,algo.predict(x_ts))

              precision    recall  f1-score   support

           0       0.88      0.86      0.87       567
           1       0.78      0.81      0.80       353

    accuracy                           0.84       920
   macro avg       0.83      0.84      0.83       920
weighted avg       0.84      0.84      0.84       920



(0.842391304347826, array([[488,  79],
        [ 66, 287]], dtype=int64))

In [12]:
from sklearn.ensemble import RandomForestClassifier
algo=RandomForestClassifier()
algo.fit(x_tr,y_tr)
print(classification_report(y_ts,algo.predict(x_ts)))
algo.score(x_ts,y_ts),confusion_matrix(y_ts,algo.predict(x_ts))

C:\Users\pulki\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


              precision    recall  f1-score   support

           0       0.89      0.91      0.90       567
           1       0.85      0.81      0.83       353

    accuracy                           0.87       920
   macro avg       0.87      0.86      0.86       920
weighted avg       0.87      0.87      0.87       920



(0.8728260869565218, array([[516,  51],
        [ 66, 287]], dtype=int64))

In [13]:
from sklearn.ensemble import AdaBoostClassifier
algo=AdaBoostClassifier()
algo.fit(x_tr,y_tr)
print(classification_report(y_ts,algo.predict(x_ts)))
algo.score(x_ts,y_ts),confusion_matrix(y_ts,algo.predict(x_ts))

              precision    recall  f1-score   support

           0       0.87      0.85      0.86       567
           1       0.77      0.79      0.78       353

    accuracy                           0.83       920
   macro avg       0.82      0.82      0.82       920
weighted avg       0.83      0.83      0.83       920



(0.8271739130434783, array([[482,  85],
        [ 74, 279]], dtype=int64))

In [14]:
from sklearn.ensemble import GradientBoostingClassifier
algo=GradientBoostingClassifier()
algo.fit(x_tr,y_tr)
print(classification_report(y_ts,algo.predict(x_ts)))
algo.score(x_ts,y_ts),confusion_matrix(y_ts,algo.predict(x_ts))

              precision    recall  f1-score   support

           0       0.89      0.87      0.88       567
           1       0.79      0.83      0.81       353

    accuracy                           0.85       920
   macro avg       0.84      0.85      0.84       920
weighted avg       0.85      0.85      0.85       920



(0.8510869565217392, array([[491,  76],
        [ 61, 292]], dtype=int64))

In [15]:
#pcA algo by hand

In [16]:
import numpy as np
a=np.arange(1,7)
a.shape=(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
from sklearn.decomposition.pca import PCA
algo=PCA(2)
algo.fit(a)
algo.transform(a),algo.components_,algo.explained_variance_

(array([[-2.82842712e+00,  2.22044605e-16],
        [ 0.00000000e+00,  0.00000000e+00],
        [ 2.82842712e+00, -2.22044605e-16]]),
 array([[ 0.70710678,  0.70710678],
        [ 0.70710678, -0.70710678]]),
 array([8.00000000e+00, 2.25080839e-33]))

In [18]:
m=a.mean(axis=0)
d=a-m
c=np.cov(d.T)
i,j=np.linalg.eig(c)
print(i,j)
np.dot(d,j.T),d,j.T

[8. 0.] [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


(array([[ 0.        , -2.82842712],
        [ 0.        ,  0.        ],
        [ 0.        ,  2.82842712]]), array([[-2., -2.],
        [ 0.,  0.],
        [ 2.,  2.]]), array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))